// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GlobalController from "./global_controller"
application.register("global", GlobalController)

import HighlightController from "./highlight_controller"
application.register("highlight", HighlightController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)
