inherit_from:
  - https://raw.githubusercontent.com/thoughtbot/guides/main/ruby/.rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 120

Metrics/PerceivedComplexity:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: true

# RSpec cops - reasonable limits for real-world tests
RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/AnyInstance:
  Exclude:
    - "spec/rails_helper.rb"  # Global stubs for external dependencies
